[project]
name = "running-mean-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.118.0",
    "pydantic>=2.11.10",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]
